PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

# Supplies the season select box from loaded game graphs.
SELECT DISTINCT ?season
WHERE {
  GRAPH ?graph {
    ?game a base:BaseballGame ;
          obo:BFO_0000199/obo:BFO_0000222 ?gameStartInstant .
    ?gameStartTimestamp a base:BaseballTimestampICE ;
                        cco:ont00001916 ?gameStartInstant ;
                        cco:ont00001767 ?gameStart .
    BIND(YEAR(?gameStart) AS ?season)
  }
}
ORDER BY DESC(?season)
