PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?pitcher ?pitcherLabel
       (COUNT(DISTINCT ?pitch) AS ?pitches)
       (COUNT(DISTINCT ?plateAppearance) AS ?plateAppearances)
       ((xsd:decimal(COUNT(DISTINCT ?pitch)) /
         COUNT(DISTINCT ?plateAppearance)) AS ?pitchesPerPlateAppearance)
WHERE {
  GRAPH ?graph {
    ?pitch a base:PitchAct ;
           obo:BFO_0000132 ?plateAppearance ;
           cco:ont00001833 ?pitcher .
    ?pitcher rdfs:label ?pitcherLabel .
  }
}
GROUP BY ?pitcher ?pitcherLabel
ORDER BY DESC(?pitchesPerPlateAppearance) LCASE(STR(?pitcherLabel))
