PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?player ?playerLabel (COUNT(DISTINCT ?swing) AS ?swings)
WHERE {
  GRAPH ?graph {
    ?swing a base:SwingAct ;
           obo:BFO_0000057 ?player .
    ?player rdfs:label ?playerLabel .
  }
}
GROUP BY ?player ?playerLabel
ORDER BY DESC(?swings) LCASE(STR(?playerLabel))
