#!/usr/bin/env python3
"""Generate small ontology and source-provenance Mermaid reviews from RML."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote

from rdflib import BNode, Graph, Literal, Namespace, RDF, RDFS, URIRef


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = (
    ROOT / "sources" / "mlb-game" / "review" / "rml-mermaid-manifest.json"
)
RR = Namespace("http://www.w3.org/ns/r2rml#")
RML = Namespace("http://semweb.mmlab.be/ns/rml#")
GENERATED_MARKER = "<!-- Generated by scripts/generate_rml_mermaid.py; do not edit. -->"


@dataclass(frozen=True)
class ObjectSpec:
    key: tuple[str, str]
    mode: str
    parent_map: str | None
    joins: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class Relation:
    predicate: URIRef
    object: ObjectSpec


@dataclass(frozen=True)
class MapInfo:
    name: str
    source: str
    source_file: str
    iterator: str
    subject_key: tuple[str, str]
    classes: tuple[URIRef, ...]
    relations: tuple[Relation, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--mapping", type=Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files are missing, extra, or stale.",
    )
    return parser.parse_args()


def load_manifest(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(
            f"{path} must use JSON syntax, which is valid YAML 1.2: {error}"
        ) from error
    if not isinstance(value, dict):
        raise ValueError(f"Manifest root must be an object: {path}")
    return value


def local_name(value: URIRef | str) -> str:
    text = str(value)
    if "#" in text:
        return unquote(text.rsplit("#", 1)[1])
    return unquote(text.rstrip("/").rsplit("/", 1)[-1])


def load_labels() -> dict[URIRef, str]:
    ontology = Graph()
    for path in sorted((ROOT / "ontology").glob("*.ttl")):
        ontology.parse(path, format="turtle")
    candidates: dict[URIRef, set[tuple[int, int, str]]] = {}
    for subject, label in ontology.subject_objects(RDFS.label):
        if isinstance(subject, URIRef) and isinstance(label, Literal):
            candidate = str(label)
            candidates.setdefault(subject, set()).add(
                (0 if label.language in {None, "en"} else 1, len(candidate), candidate)
            )
    labels = {
        subject: min(subject_candidates)[2]
        for subject, subject_candidates in candidates.items()
    }
    labels[URIRef("http://purl.org/dc/terms/identifier")] = "identifier"
    labels[RDFS.label] = "label"
    return labels


def readable_uri(value: URIRef, labels: dict[URIRef, str]) -> str:
    return labels.get(value, local_name(value))


def term_key(graph: Graph, term_map: BNode | URIRef) -> tuple[str, str]:
    template = graph.value(term_map, RR.template)
    if template is not None:
        return ("template", str(template))
    constant = graph.value(term_map, RR.constant)
    if constant is not None:
        return ("constant", str(constant))
    reference = graph.value(term_map, RML.reference) or graph.value(term_map, RR.column)
    if reference is not None:
        return ("reference", str(reference))
    return ("anonymous", str(term_map))


def map_name(value: URIRef) -> str:
    return local_name(value)


def parse_mapping(path: Path) -> tuple[Graph, dict[str, MapInfo]]:
    graph = Graph().parse(path, format="turtle")
    infos: dict[str, MapInfo] = {}
    for triples_map in sorted(graph.subjects(RDF.type, RR.TriplesMap), key=str):
        if not isinstance(triples_map, URIRef):
            raise ValueError(f"Triples map must have an IRI: {triples_map}")
        name = map_name(triples_map)
        logical_sources = list(graph.objects(triples_map, RML.logicalSource))
        subject_maps = list(graph.objects(triples_map, RR.subjectMap))
        if len(logical_sources) != 1 or len(subject_maps) != 1:
            raise ValueError(
                f"{name} must have exactly one logical source and one subject map"
            )
        logical_source = logical_sources[0]
        subject_map = subject_maps[0]
        source_name = local_name(logical_source)
        source_file = str(graph.value(logical_source, RML.source) or "")
        iterator = str(graph.value(logical_source, RML.iterator) or "")
        classes = tuple(
            sorted(
                (value for value in graph.objects(subject_map, RR["class"]) if isinstance(value, URIRef)),
                key=str,
            )
        )
        relations: list[Relation] = []
        for predicate_object_map in graph.objects(triples_map, RR.predicateObjectMap):
            predicates = [
                value
                for value in graph.objects(predicate_object_map, RR.predicate)
                if isinstance(value, URIRef)
            ]
            object_maps = list(graph.objects(predicate_object_map, RR.objectMap))
            direct_objects = list(graph.objects(predicate_object_map, RR.object))
            for predicate in predicates:
                for object_map in object_maps:
                    parent = graph.value(object_map, RR.parentTriplesMap)
                    joins = tuple(
                        sorted(
                            (
                                str(graph.value(join, RR.child) or ""),
                                str(graph.value(join, RR.parent) or ""),
                            )
                            for join in graph.objects(object_map, RR.joinCondition)
                        )
                    )
                    if isinstance(parent, URIRef):
                        parent_subject = graph.value(parent, RR.subjectMap)
                        if parent_subject is None:
                            raise ValueError(f"{name} references parent map without a subject: {parent}")
                        spec = ObjectSpec(
                            key=term_key(graph, parent_subject),
                            mode="join",
                            parent_map=map_name(parent),
                            joins=joins,
                        )
                    else:
                        key = term_key(graph, object_map)
                        mode = "literal" if key[0] == "reference" else "template"
                        constant = graph.value(object_map, RR.constant)
                        if isinstance(constant, Literal):
                            mode = "literal"
                        spec = ObjectSpec(key=key, mode=mode, parent_map=None, joins=joins)
                    relations.append(Relation(predicate=predicate, object=spec))
                for direct_object in direct_objects:
                    mode = "literal" if isinstance(direct_object, Literal) else "constant"
                    relations.append(
                        Relation(
                            predicate=predicate,
                            object=ObjectSpec(
                                key=(mode, str(direct_object)),
                                mode=mode,
                                parent_map=None,
                                joins=(),
                            ),
                        )
                    )
        if name in infos:
            raise ValueError(f"Duplicate triples-map local name: {name}")
        infos[name] = MapInfo(
            name=name,
            source=source_name,
            source_file=source_file,
            iterator=iterator,
            subject_key=term_key(graph, subject_map),
            classes=classes,
            relations=tuple(relations),
        )
    return graph, infos


def validate_manifest(manifest: dict, infos: dict[str, MapInfo]) -> list[dict]:
    if manifest.get("version") != 1:
        raise ValueError("Manifest version must be 1")
    patterns = manifest.get("patterns")
    if not isinstance(patterns, list) or not patterns:
        raise ValueError("Manifest patterns must be a non-empty array")
    limits = manifest.get("limits", {})
    max_maps = int(limits.get("maps_per_pattern", 15))
    seen_ids: set[str] = set()
    assigned: set[str] = set()
    errors: list[str] = []
    for pattern in patterns:
        identifier = pattern.get("id")
        if not isinstance(identifier, str) or not re.fullmatch(r"[0-9]{2}-[a-z0-9-]+", identifier):
            errors.append(f"Invalid pattern id: {identifier!r}")
            continue
        if identifier in seen_ids:
            errors.append(f"Duplicate pattern id: {identifier}")
        seen_ids.add(identifier)
        if not isinstance(pattern.get("title"), str) or not pattern["title"].strip():
            errors.append(f"Pattern {identifier} has no title")
        if not isinstance(pattern.get("summary"), str) or not pattern["summary"].strip():
            errors.append(f"Pattern {identifier} has no summary")
        maps = pattern.get("maps")
        if not isinstance(maps, list) or not maps:
            errors.append(f"Pattern {identifier} has no maps")
            continue
        if len(maps) != len(set(maps)):
            errors.append(f"Pattern {identifier} repeats a map")
        if len(maps) > max_maps:
            errors.append(
                f"Pattern {identifier} has {len(maps)} maps; limit is {max_maps}"
            )
        unknown = sorted(set(maps) - set(infos))
        if unknown:
            errors.append(
                f"Pattern {identifier} references missing maps: {', '.join(unknown)}"
            )
        assigned.update(set(maps) & set(infos))
    unassigned = sorted(set(infos) - assigned)
    if unassigned:
        errors.append(
            f"Unassigned triples maps ({len(unassigned)}): {', '.join(unassigned)}"
        )
    if errors:
        raise ValueError("Manifest validation failed:\n- " + "\n- ".join(errors))
    return patterns


def markdown_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def mermaid_escape(text: str) -> str:
    return (
        text.replace("&", "and")
        .replace('"', "'")
        .replace("<", "")
        .replace(">", "")
        .replace("{", "(")
        .replace("}", ")")
        .replace("|", "/")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def template_hint(key: tuple[str, str]) -> str:
    kind, value = key
    if kind in {"literal", "reference"}:
        return "Literal value"
    if kind == "constant":
        return local_name(value).replace("-", " ").title()
    pieces = [
        piece
        for piece in re.sub(r"\{[^}]+\}", "", value).rstrip("/").split("/")
        if piece
    ]
    if not pieces:
        return "Mapped resource"
    return pieces[-1].replace("-", " ").replace("_", " ").title()


def classes_for_key(
    key: tuple[str, str], selected: list[MapInfo], all_infos: dict[str, MapInfo]
) -> tuple[URIRef, ...]:
    local = {
        class_
        for info in selected
        if info.subject_key == key
        for class_ in info.classes
    }
    if local:
        return tuple(sorted(local, key=str))
    global_classes = {
        class_
        for info in all_infos.values()
        if info.subject_key == key
        for class_ in info.classes
    }
    return tuple(sorted(global_classes, key=str))


def identity_label(
    key: tuple[str, str],
    selected: list[MapInfo],
    all_infos: dict[str, MapInfo],
    labels: dict[URIRef, str],
) -> str:
    classes = classes_for_key(key, selected, all_infos)
    class_labels = sorted({readable_uri(value, labels) for value in classes})
    if class_labels and len(class_labels) <= 3:
        return " / ".join(class_labels)
    return template_hint(key)


def semantic_page(
    pattern: dict,
    infos: dict[str, MapInfo],
    labels: dict[URIRef, str],
    fingerprint: str,
    limits: dict,
) -> str:
    selected = [infos[name] for name in pattern["maps"]]
    include_literals = bool(pattern.get("include_literals", False))
    keys: set[tuple[str, str]] = {info.subject_key for info in selected}
    edge_specs: set[tuple[tuple[str, str], str, tuple[str, str]]] = set()
    for info in selected:
        for relation in info.relations:
            if relation.object.mode == "literal" and not include_literals:
                continue
            keys.add(relation.object.key)
            edge_specs.add(
                (
                    info.subject_key,
                    readable_uri(relation.predicate, labels),
                    relation.object.key,
                )
            )
    max_nodes = int(limits.get("semantic_nodes_per_pattern", 20))
    max_edges = int(limits.get("semantic_edges_per_pattern", 36))
    if len(keys) > max_nodes or len(edge_specs) > max_edges:
        raise ValueError(
            f"Pattern {pattern['id']} semantic view is too large: "
            f"{len(keys)} nodes/{len(edge_specs)} edges; limits are "
            f"{max_nodes}/{max_edges}"
        )
    ordered_keys = sorted(keys)
    node_ids = {key: f"N{index:02d}" for index, key in enumerate(ordered_keys, 1)}
    lines = ["flowchart LR"]
    for key in ordered_keys:
        label = identity_label(key, selected, infos, labels)
        lines.append(f'    {node_ids[key]}["{mermaid_escape(label)}"]')
    for subject, predicate, object_ in sorted(
        edge_specs,
        key=lambda item: (node_ids[item[0]], item[1], node_ids[item[2]]),
    ):
        lines.append(
            f"    {node_ids[subject]} -->|{mermaid_escape(predicate)}| {node_ids[object_]}"
        )
    maps_text = ", ".join(f"`{name}`" for name in pattern["maps"])
    return "\n".join(
        [
            GENERATED_MARKER,
            f"<!-- Mapping SHA-256: {fingerprint} -->",
            "",
            f"# {pattern['title']}",
            "",
            pattern["summary"],
            "",
            "This view shows the ontology pattern without MLB JSON paths or RML machinery.",
            "",
            "```mermaid",
            *lines,
            "```",
            "",
            "## RML evidence boundary",
            "",
            f"Generated from: {maps_text}.",
            "",
        ]
    )


def choose_target_map(
    object_: ObjectSpec,
    selected_names: list[str],
    infos: dict[str, MapInfo],
) -> str | None:
    if object_.parent_map:
        return object_.parent_map
    candidates = [
        name for name, info in infos.items() if info.subject_key == object_.key
    ]
    if not candidates:
        return None
    order = {name: index for index, name in enumerate(selected_names)}
    return min(
        candidates,
        key=lambda name: (
            0 if name in order else 1,
            order.get(name, 999999),
            0 if infos[name].classes else 1,
            name,
        ),
    )


def source_page(
    pattern: dict,
    infos: dict[str, MapInfo],
    labels: dict[URIRef, str],
    fingerprint: str,
    limits: dict,
) -> str:
    selected_names = pattern["maps"]
    selected = [infos[name] for name in selected_names]
    node_ids = {name: f"M{index:02d}" for index, name in enumerate(selected_names, 1)}
    sources = sorted({info.source for info in selected})
    source_ids = {name: f"S{index:02d}" for index, name in enumerate(sources, 1)}
    external_targets: dict[str, set[str]] = {name: set() for name in selected_names}
    relation_lines: set[str] = set()
    for info in selected:
        for relation in info.relations:
            if relation.object.mode == "literal":
                continue
            target_map = choose_target_map(relation.object, selected_names, infos)
            if target_map in node_ids:
                target_id = node_ids[target_map]
            else:
                target_label = target_map or identity_label(
                    relation.object.key, selected, infos, labels
                )
                predicate = readable_uri(relation.predicate, labels)
                mode = "join" if relation.object.mode == "join" else "template"
                external_targets[info.name].add(
                    f"{predicate} -> {target_label} ({mode})"
                )
                continue
            predicate = readable_uri(relation.predicate, labels)
            mode = "join" if relation.object.mode == "join" else "template"
            arrow = "-->" if mode == "join" else "-.->"
            relation_lines.add(
                f"    {node_ids[info.name]} {arrow}|{mermaid_escape(predicate)}; {mode}| {target_id}"
            )
    source_node_count = len(sources) + len(selected)
    source_edge_count = len(selected) + len(relation_lines)
    max_nodes = int(limits.get("source_nodes_per_pattern", 18))
    max_edges = int(limits.get("source_edges_per_pattern", 26))
    if source_node_count > max_nodes or source_edge_count > max_edges:
        raise ValueError(
            f"Pattern {pattern['id']} source view is too large: "
            f"{source_node_count} nodes/{source_edge_count} edges; limits are "
            f"{max_nodes}/{max_edges}"
        )
    lines = ["flowchart LR"]
    for source in sources:
        lines.append(f'    {source_ids[source]}["Source: {mermaid_escape(source)}"]')
    for info in selected:
        class_labels = [readable_uri(value, labels) for value in info.classes]
        suffix = " / ".join(class_labels) if class_labels else "relationship overlay"
        lines.append(
            f'    {node_ids[info.name]}["{mermaid_escape(info.name)}<br/>{mermaid_escape(suffix)}"]'
        )
    for info in selected:
        lines.append(f"    {source_ids[info.source]} --> {node_ids[info.name]}")
    lines.extend(sorted(relation_lines))

    source_rows = []
    for source in sources:
        source_info = next(info for info in selected if info.source == source)
        count = sum(1 for info in selected if info.source == source)
        source_rows.append(
            f"| `{source}` | `{markdown_escape(source_info.source_file)}` | "
            f"`{markdown_escape(source_info.iterator)}` | {count} |"
        )
    map_rows = []
    for info in selected:
        class_text = ", ".join(readable_uri(value, labels) for value in info.classes)
        if not class_text:
            class_text = "relationship overlay"
        relations = sorted({readable_uri(item.predicate, labels) for item in info.relations})
        relation_text = ", ".join(relations) if relations else "type assertion only"
        target_text = ", ".join(sorted(external_targets[info.name])) or "none"
        map_rows.append(
            f"| `{info.name}` | {markdown_escape(class_text)} | {markdown_escape(relation_text)} | {markdown_escape(target_text)} |"
        )
    return "\n".join(
        [
            GENERATED_MARKER,
            f"<!-- Mapping SHA-256: {fingerprint} -->",
            "",
            f"# {pattern['title']} - MLB game RML",
            "",
            pattern["summary"],
            "",
            "Solid relation arrows are explicit parent-triples-map joins. Dotted relation arrows are IRI-template matches inferred by the reviewer from the actual RML templates. Cross-pattern targets are listed in the table rather than drawn, keeping the diagram small.",
            "",
            "```mermaid",
            *lines,
            "```",
            "",
            "## Logical sources",
            "",
            "| Source | Execution file | JSONPath iterator | Maps in this review |",
            "| --- | --- | --- | ---: |",
            *source_rows,
            "",
            "## Triples maps",
            "",
            "| Triples map | Subject class | Emitted relations | Cross-pattern targets |",
            "| --- | --- | --- | --- |",
            *map_rows,
            "",
        ]
    )


def catalog_readme(
    title: str,
    introduction: str,
    directory: str,
    patterns: list[dict],
    fingerprint: str,
) -> str:
    rows = [
        f"| [{pattern['title']}]({pattern['id']}.md) | {len(pattern['maps'])} |"
        for pattern in patterns
    ]
    return "\n".join(
        [
            GENERATED_MARKER,
            f"<!-- Mapping SHA-256: {fingerprint} -->",
            "",
            f"# {title}",
            "",
            introduction,
            "",
            "| Review pattern | RML maps providing evidence |",
            "| --- | ---: |",
            *rows,
            "",
            f"Catalog directory: `{directory}`.",
            "",
        ]
    )


def root_readme(patterns: list[dict], fingerprint: str, map_count: int) -> str:
    rows = [
        "| "
        + pattern["title"]
        + f" | [Ontology pattern](ontology/{pattern['id']}.md) "
        + f"| [MLB game mapping](mlb-game/{pattern['id']}.md) "
        + f"| {len(pattern['maps'])} |"
        for pattern in patterns
    ]
    return "\n".join(
        [
            GENERATED_MARKER,
            f"<!-- Mapping SHA-256: {fingerprint} -->",
            "",
            "# Generated RML pattern reviews",
            "",
            "These catalogs are generated from the active RML plus the reviewed pattern boundaries in `../../sources/mlb-game/review/rml-mermaid-manifest.json`. Do not edit generated pages directly.",
            "",
            "- `ontology/` shows each RDF/ontology pattern without source-specific mechanics.",
            "- `mlb-game/` shows how the MLB game source module's logical sources and triples maps emit that pattern.",
            "- Solid mapping-view relation arrows are explicit joins; dotted arrows are matching IRI templates.",
            "",
            f"The manifest assigns all {map_count} triples maps. The mapping fingerprint is `{fingerprint}`.",
            "",
            "| Pattern | Source-independent review | Source-specific review | Maps |",
            "| --- | --- | --- | ---: |",
            *rows,
            "",
            "## Regenerate and validate",
            "",
            "```powershell",
            "python Baseball/scripts/generate_rml_mermaid.py",
            "python Baseball/scripts/generate_rml_mermaid.py --check",
            "```",
            "",
            "Generation and validation fail when a triples map is unassigned, a manifest map does not exist, a pattern exceeds the configured review-size limits, or committed output is stale.",
            "",
        ]
    )


def build_outputs(
    manifest: dict,
    patterns: list[dict],
    infos: dict[str, MapInfo],
    labels: dict[URIRef, str],
    fingerprint: str,
) -> tuple[Path, dict[Path, str]]:
    output_root = (ROOT / manifest["output_root"]).resolve()
    expected_root = (ROOT / "mermaid" / "patterns").resolve()
    if output_root != expected_root:
        raise ValueError(f"Output root must be {expected_root}, got {output_root}")
    outputs: dict[Path, str] = {}
    outputs[output_root / "README.md"] = root_readme(
        patterns, fingerprint, len(infos)
    )
    outputs[output_root / "ontology" / "README.md"] = catalog_readme(
        "Source-independent ontology patterns",
        "These diagrams review the RDF pattern itself, independent of MLB JSON paths and RML implementation details.",
        "ontology",
        patterns,
        fingerprint,
    )
    outputs[output_root / "mlb-game" / "README.md"] = catalog_readme(
        "MLB game mapping patterns",
        "These diagrams review the logical sources, triples maps, joins, and matching IRI templates used by the MLB game source module.",
        "mlb-game",
        patterns,
        fingerprint,
    )
    limits = manifest.get("limits", {})
    for pattern in patterns:
        outputs[output_root / "ontology" / f"{pattern['id']}.md"] = semantic_page(
            pattern, infos, labels, fingerprint, limits
        )
        outputs[output_root / "mlb-game" / f"{pattern['id']}.md"] = source_page(
            pattern, infos, labels, fingerprint, limits
        )
    return output_root, outputs


def check_outputs(output_root: Path, outputs: dict[Path, str]) -> None:
    expected = set(outputs)
    actual = set(output_root.rglob("*.md")) if output_root.exists() else set()
    problems: list[str] = []
    for path in sorted(expected - actual):
        problems.append(f"missing generated file: {path.relative_to(ROOT)}")
    for path in sorted(actual - expected):
        problems.append(f"extra generated file: {path.relative_to(ROOT)}")
    for path in sorted(expected & actual):
        if path.read_text(encoding="utf-8") != outputs[path]:
            problems.append(f"stale generated file: {path.relative_to(ROOT)}")
    if problems:
        raise ValueError("Generated Mermaid validation failed:\n- " + "\n- ".join(problems))


def write_outputs(output_root: Path, outputs: dict[Path, str]) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    expected = set(outputs)
    for path in sorted(output_root.rglob("*.md"), reverse=True):
        if path not in expected:
            path.unlink()
    for path, content in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    for directory in sorted(
        (path for path in output_root.rglob("*") if path.is_dir()), reverse=True
    ):
        if not any(directory.iterdir()):
            try:
                directory.rmdir()
            except PermissionError:
                # OneDrive may retain an empty reparse-point placeholder after
                # tracked generated files move. Empty placeholders are harmless.
                pass


def main() -> None:
    args = parse_args()
    manifest_path = args.manifest.resolve()
    manifest = load_manifest(manifest_path)
    mapping_path = (
        args.mapping.resolve()
        if args.mapping
        else (ROOT / manifest["mapping"]).resolve()
    )
    fingerprint = hashlib.sha256(mapping_path.read_bytes()).hexdigest()
    _, infos = parse_mapping(mapping_path)
    patterns = validate_manifest(manifest, infos)
    labels = load_labels()
    output_root, outputs = build_outputs(
        manifest, patterns, infos, labels, fingerprint
    )
    if args.check:
        check_outputs(output_root, outputs)
        action = "validated"
    else:
        write_outputs(output_root, outputs)
        action = "generated"
    print(
        f"RML Mermaid {action}: {len(patterns)} patterns, {len(infos)} triples maps, "
        f"{len(outputs)} Markdown files"
    )
    print(f"Mapping SHA-256: {fingerprint}")


if __name__ == "__main__":
    try:
        main()
    except (KeyError, OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1) from error
