PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?game
       (MIN(?gameStartValue) AS ?gameStart)
       (MAX(?gameEndValue) AS ?gameEnd)
WHERE {
  GRAPH ?graph {
    ?game a base:BaseballGame ;
          obo:BFO_0000199 ?interval .
    ?interval obo:BFO_0000222 ?startInstant ;
              obo:BFO_0000224 ?endInstant .
    ?startTimestamp a base:BaseballTimestampICE ;
                    cco:ont00001916 ?startInstant ;
                    cco:ont00001808 ?game ;
                    cco:ont00001767 ?gameStartValue .
    ?endTimestamp a base:BaseballTimestampICE ;
                  cco:ont00001916 ?endInstant ;
                  cco:ont00001808 ?game ;
                  cco:ont00001767 ?gameEndValue .
  }
}
GROUP BY ?game
ORDER BY ?gameStart
