PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?season ?player ?playerLabel
       (COUNT(DISTINCT ?hit) AS ?hits)
       (COUNT(DISTINCT ?game) AS ?gamesWithHits)
WHERE {
  GRAPH ?graph {
    ?game a base:BaseballGame ;
          obo:BFO_0000199/obo:BFO_0000222 ?gameStartInstant .
    ?gameStartTimestamp a base:BaseballTimestampICE ;
                        cco:ont00001916 ?gameStartInstant ;
                        cco:ont00001767 ?gameStart .

    ?hit a base:BaseballInstitutionalProcess, ?hitClass ;
         obo:BFO_0000132 ?plateAppearance ;
         obo:BFO_0000117 ?hitJudgment .
    ?hitJudgment a base:HitJudgmentAct .
    ?plateAppearance a base:PlateAppearance ;
                     obo:BFO_0000132/obo:BFO_0000132/obo:BFO_0000132 ?game .
    ?batterAct a base:BatterAct ;
               obo:BFO_0000132 ?plateAppearance ;
               obo:BFO_0000057 ?player .
    ?player rdfs:label ?playerLabel .

    VALUES ?hitClass {
      base:SingleProcess base:DoubleProcess base:TripleProcess base:HomeRunProcess
    }
    BIND(YEAR(?gameStart) AS ?season)
  }
}
GROUP BY ?season ?player ?playerLabel
ORDER BY ?season DESC(?hits) LCASE(STR(?playerLabel))
