PREFIX base: <https://baseballontology.org/>
PREFIX cco: <https://www.commoncoreontologies.org/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?game ?player ?playerLabel (COUNT(DISTINCT ?result) AS ?hits)
WHERE {
  GRAPH ?graph {
    ?game a base:BaseballGame .
    ?result a base:BaseballInstitutionalProcess, ?hitClass ;
            obo:BFO_0000132 ?plateAppearance ;
            obo:BFO_0000117 ?hitJudgment .
    ?hitJudgment a base:HitJudgmentAct .
    ?plateAppearance a base:PlateAppearance ;
                     obo:BFO_0000132/obo:BFO_0000132/obo:BFO_0000132 ?game .
    ?batterAct a base:BatterAct ;
               obo:BFO_0000132 ?plateAppearance ;
               obo:BFO_0000057 ?player .
    ?player rdfs:label ?playerLabel .
    VALUES ?hitClass {
      base:SingleProcess base:DoubleProcess base:TripleProcess base:HomeRunProcess
    }
  }
}
GROUP BY ?game ?player ?playerLabel
HAVING(COUNT(DISTINCT ?result) >= 2)
ORDER BY DESC(?hits) LCASE(STR(?playerLabel)) ?game
